{
	"name": "Hewalex2MQTT-PCCO-Mono",
	"version": "0.0.90",
	"slug": "hewalex",
	"description": "Monitoring pomp ciepła Hewalex PCCO Mono",
	"url": "https://github.com/oley83/hewalex2mqtt_pcco/",
	"arch": [
		"armv7",
		"aarch64",
		"amd64",
		"i386"
	],
	"startup": "application",
	"init": "false",
	"boot": "auto",
	"host_network": "true",
	"options": {
		"mqtt_ip": "core-mosquitto",
		"mqtt_port": 1883,
		"mqtt_authentication": true,
		"mqtt_user": "mqtt",
		"mqtt_pass": "mqtt_narcyzowa",
		"Read_only_mode": true,
		"Read_config_enabled": false,
		"Print_mqtt_topics": false,
		"Serial_timeout": 10,
  		"Max_retries": 2,
  		"Polling_interval": 60,
		"Device_Pcco_Enabled": true,
		"Device_Pcco_Address": "192.168.0.70",
		"Device_Pcco_Port": 4196,
		"Device_Pcco_MqttTopic": "PCCO Mono"
	},
"schema": {
    "mqtt_ip": {
        "name": "Adres IP Brokera MQTT",
        "description": "Wpisz adres IP lub nazwę hosta (np. core-mosquitto).",
        "type": "str"
    },
    "mqtt_port": {
        "name": "Port MQTT",
        "description": "Domyślnie 1883.",
        "type": "port"
    },
    "mqtt_authentication": {
        "name": "Wymagane uwierzytelnienie",
        "type": "bool"
    },
    "Read_only_mode": {
        "name": "Tryb tylko do odczytu",
        "description": "Zapobiega wysyłaniu poleceń sterujących do pompy ciepła.",
        "type": "bool"
    },
    // ... i analogicznie dla wszystkich pozostałych zmiennych
    "Device_Pcco_MqttTopic": {
        "name": "Bazowy Temat MQTT dla PCCO",
        "type": "str"
    }
}
}
